config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  root 'home#main_page'
  get 'my_page/index'
  resources :musics
  
  get 'home/fake_page' =>'home#fake_page'
  
  post "tapes/likes/:tape_id/create" => "likes#create"
  post "tapes/likes/:tape_id/destroy" => "like#destroy"
  post "daily/likes/:daily_id/create" => "likes#create"
  post "/daily/likes/:daily_id/create" => "likes#create"
  post "likes/:daily_id/create" => "likes#create"
  post "likes/:tape_id/create" => "likes#create"
  post "daily/likes/:daily_id/destroy" => "like#destroy"
  
  get '/tapes/new' =>'tapes#new'
  post '/tapes' =>'tapes#create'
  
  get '/tapes' => 'tapes#index'
  get '/tapes/:id' => 'tapes#show'
  
  get '/tapes/:id/edit' => 'tapes#edit'
  patch'/tapes/:id' =>'tapes#update'
  
  delete '/tapes/:id' => 'tapes#destroy'
  
  get '/daily' => 'daily#index'
  
  get '/daily/new' => 'daily#new'
  post '/daily' => 'daily#create'
  
  get '/daily/:id' => 'daily#show'
  
  get '/daily/:id/edit' => 'daily#edit'
  patch '/daily/:id' => 'daily#update'
  
  delete '/daily/:id' => 'daily#destroy'
  
  
  
  

end

app/models/tape.rb
class Tape < ActiveRecord::Base
    belongs_to :user
    belongs_to :music
    
    mount_uploader :image, S3Uploader
    
#    def music_name
#        music.try(:name)
#    end
#    
#    def music_name=(name)
#        self.music = Music.find_by_name(name) if name.persent?
#    end
#    
#    def singer_name
#        music.try(:singer)
#    end
#    
#    def music_singer=(singer)
#        self.music = Music.find_by_singer(singer) if singer.persent?
#    end
end

app/controllers/tapes_controller.rb
class TapesController < ApplicationController
 #CREATE
  def new 
    @token = form_authenticity_token
    @userID = current_user.id
    @musics = Music.all
    
    @musictitles = Array.new()
    @musics.each do |music|
      @musictitles.push music.title
    end
    
    @musicsingers = Array.new()
    @musics.each do |music|
      @musicsingers.push music.singer
    end
  end
  
  def create
   
    tape = Tape.new
    
    tape.image = params[:img_input]
    
    tape.user_id = params[:user_id]
    tape.title = params[:input_title]
    
    tape.m1_title = params[:music1]
    tape.m1_singer = params[:singer1]
    
    tape.m2_title = params[:music2]
    tape.m2_singer = params[:singer2]
    
    tape.m3_title = params[:music3]
    tape.m3_singer = params[:singer3]
    
    tape.m4_title = params[:music4]
    tape.m4_singer = params[:singer4]
    
    tape.m5_title = params[:music5]
    tape.m5_singer = params[:singer5]
    
    tape.m6_title = params[:music6]
    tape.m6_singer = params[:singer6]
    
    tape.m7_title = params[:music7]
    tape.m7_singer = params[:singer7]
    
    tape.m8_title = params[:music8]
    tape.m8_singer = params[:singer8]
    
    tape.m9_title = params[:music9]
    tape.m9_singer = params[:singer9]
    
    tape.m10_title = params[:music10]
    tape.m10_singer = params[:singer10]
    
    tape.save
    redirect_to "/my_page/index"
    # TODO:뮤직과 싱어를 더 추가 해야 해욤.
  end
  
  #READ
  
  def index
    @tapes = Tape.all
  end
  
  def show
    @tape = Tape.find params[:id]
    @token = form_authenticity_token
  end
  
  # UPDATE
  def edit
    @tape =Tape.find params[:id]
    @token = form_authenticity_token
    
  end
  
  def update
    tape = Tape.find params[:id]
    
    tape.title = params[:input_title]
    tape.m1_title = params[:music1]
    tape.m1_singer = params[:singer1]
    tape.m2_title = params[:music2]
    tape.m2_singer = params[:singer2]
    tape.m3_title = params[:music3]
    tape.m3_singer = params[:singer3]
    tape.m4_title = params[:music4]
    tape.m4_singer = params[:singer4]
    tape.m5_title = params[:music5]
    tape.m5_singer = params[:singer5]
    tape.m6_title = params[:music6]
    tape.m6_singer = params[:singer6]
    tape.m7_title = params[:music7]
    tape.m7_singer = params[:singer7]
    tape.m8_title = params[:music8]
    tape.m8_singer = params[:singer8]
    tape.m9_title = params[:music9]
    tape.m9_singer = params[:singer9]
    tape.m10_title = params[:music10]
    tape.m10_singer = params[:singer10]
    tape.save
    redirect_to "/my_page/index"
  end
  # DESTROY
  
  def destroy
    @tape = Tape.find params[:id]
    @tape.destroy
    
    redirect_to '/my_page/index' 
    #액션의 끝은 어디론가 가야함.
    
  end
  

end

app/helpers/tapes_helper.rb
module TapesHelper
end

app/views/tapes/_form.html.erb
<%= form_for Tape.new do |f| %>
    <div class="field">
        <%= f.label :music_name %><br />
        <%= f.text_field :music_name, data: {autocomplete_source: musics_path} %>
    </div>
    <div class="field">
        <%= f.label :singer_name %><br />
        <%= f.text_field :singer_name %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/tapes/edit.html.erb
<script>
    $(function(){
        var index = <%=raw @musictitles %>
        $(".music").autocomplete({
            source: index
        });
    });
    $(function(){
        var index = <%=raw @musicsingers %>
        $(".singer").autocomplete({
            source: index
        });
    });
</script>

<section class="tape_edit">
<div class="d-flex justify-content-center">
<div class="w-50 p-3"><br><br>
<h1 class="tape_edit_title">tape 수정하기</h1><br>
<div class="tape_edit">

<form action='/tapes/<%= @tape.id%>' method='POST'>
    
    <input type="hidden" name="_method" value="patch"></input>
    <input type='hidden' name='authenticity_token' value=<%=@token %>></input>
   
    <label for="input_title">Tape Name</label>
    <input name='input_title' type='text' placeholder='tape name' value="<%= @tape.title%>"></input><br>
    
    <label for="music1">Music</label>
    <input class="music" name='music1' type='text' value="<%= @tape.m1_title%>"></input>
    <label for="singer1">Singer</label>
    <input class="singer" name='singer1' type='text' value="<%= @tape.m1_singer%>"></input><br>
    
    <label for="music2">Music</label>
    <input class="music" name='music2' type='text' value="<%= @tape.m2_title%>"></input>
    <label for="singer2">Singer</label>
    <input class="singer" name='singer2' type='text' value="<%= @tape.m2_singer%>"></input><br>

    <label for="music3">Music</label>
    <input class="music" name='music3' type='text' value="<%= @tape.m3_title%>"></input>
    <label for="singer3">Singer</label>
    <input class="singer" name='singer3' type='text' value="<%= @tape.m3_singer%>"></input><br>
    
    <label for="music4">Music</label>
    <input class="music" name='music4' type='text' value="<%= @tape.m4_title%>"></input>
    <label for="singer4">Singer</label>
    <input class="singer" name='singer4' type='text' value="<%= @tape.m4_singer%>"></input><br>

    <label for="music5">Music</label>
    <input class="music" name='music5' type='text' value="<%= @tape.m5_title%>"></input>
    <label for="singer5">Singer</label>
    <input class="singer" name='singer5' type='text' value="<%= @tape.m5_singer%>"></input><br>
    
    <label for="music6">Music</label>
    <input class="music" name='music6' type='text' value="<%= @tape.m6_title%>"></input>
    <label for="singer6">Singer</label>
    <input class="singer" name='singer6' type='text' value="<%= @tape.m6_singer%>"></input><br>
   
    <label for="music7">Music</label>
    <input class="music" name='music7' type='text' value="<%= @tape.m7_title%>"></input>
    <label for="singer7">Singer</label>
    <input class="singer" name='singer7' type='text' value="<%= @tape.m7_singer%>"></input><br>
    
    <label for="music8">Music</label>
    <input class="music" name='music8' type='text' value="<%= @tape.m8_title%>"></input>
    <label for="singer8">Singer</label>
    <input class="singer" name='singer8' type='text' value="<%= @tape.m8_singer%>"></input><br>
    
    <label for="music9">Music</label>
    <input class="music" name='music9' type='text' value="<%= @tape.m9_title%>"></input>
    <label for="singer9">Singer</label>
    <input class="singer" name='singer9' type='text' value="<%= @tape.m9_singer%>"></input><br>
    
    <label for="music10">Music</label>
    <input class="music" name='music10' type='text' value="<%= @tape.m10_title%>"></input>
    <label for="singer10">Singer</label>
    <input class="singer" name='singer10' type='text' value="<%= @tape.m10_singer%>"></input>
    
     <input type='file' name='img_input' value=<%= @tape.image%>></input><br>
    <button type='submit' value='save' class="btn btn-secondary">등록</button>
</form>
</div>
</div>
</div>
</section>

app/views/tapes/index.html.erb
<!--daily 연습-->

<h1>모든 Tape list</h1>

<div class="containter">
    <div class="row">
     <% @tapes.each do |tape| %>
        <div class="col-12 col-md-4 col-lg-4">
            <div class="tape">
             <%= image_tag "#{tape.image}" , class: " no_img_size "%>
             <div class="tape_name"><%= tape.title %></div>
             <%= image_tag "tape_grey.png", class: " tape_grey_img " %>
            </div>
        </div>
     <% end%>
    </div>
</div>

app/views/tapes/new.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>

<script>
    $(function(){
        var index = <%=raw @musictitles %>
        $(".music").autocomplete({
            source: index
        });
    });
    $(function(){
        var index = <%=raw @musicsingers %>
        $(".singer").autocomplete({
            source: index
        });
    });
</script>
<form action='/tapes' method='POST' enctype='multipart/form-data'>
    <%= hidden_field_tag :authenticity_token,form_authenticity_token%>
    <input name='authenticity_token' type='hidden'value=<%= @token%>></input>
    <input name='user_id' type='hidden' value=<%= @userID %>></input>
    
<section class="tape_form">
    <div class="d-flex justify-content-center">
    <div class="w-50 p-3">
        <h1 class="post_intro">one day, one tape</h1>
<br>
<form>           
    <label>Tape Name <input name='input_title' type='text' class="form-control" placeholder='tape name'></input> </label>
   <br>
    <label>Music <input class='music' name='music1' type='text' autocomplete='off'></input></label>
    <label>Singer <input class='singer' name='singer1' type='text' autocomplete='off'></input></label>
    <br>
    
    <label>Music <input class='music' name='music2' type='text' autocomplete='off'></input></label>
    <label>Singer <input class='singer' name='singer2' type='text' autocomplete='off'></input></label>
    <br>
    
    <label>Music <input class='music' name='music3' type='text' autocomplete='off'></input></label>
    <label>Singer <input class='singer' name='singer3' type='text' autocomplete='off'></input></label>
    <br>
    
    <label>Music <input class='music' name='music4' type='text' autocomplete='off'></input></label>
    <label>Singer <input class='singer' name='singer4' type='text' autocomplete='off'></input></label>
    <br>

    <label>Music <input class='music' name='music5' type='text' autocomplete='off'></input></label>
    <label>Singer <input class='singer' name='singer5' type='text' autocomplete='off'></input></label>
    <br>
    
    <label>Music <input class='music' name='music6' type='text' autocomplete='off'></input></label>
    <label>Singer <input class='singer' name='singer6' type='text' autocomplete='off'></input></label>
    <br>

    <label>Music <input class='music' name='music7' type='text' autocomplete='off'></input></label>
    <label>Singer <input  class='singer' name='singer7' type='text' autocomplete='off'></input></label>
    <br>
    
    <label>Music <input class='music' name='music8' type='text' autocomplete='off'></input></label>
    <label>Singer <input class='singer' name='singer8' type='text' autocomplete='off'></input></label>
    <br>

    <label>Music <input class='music' name='music9' type='text' autocomplete='off'></input></label>
    <label>Singer <input class='singer' name='singer9' type='text' autocomplete='off'></input></label>
    <br>
    
    <label>Music <input class='music' name='music10' type='text' autocomplete='off'></input></label>
    <label>Singer <input class='singer' name='singer10' type='text' autocomplete='off'></input></label>
    <br>

    <label>tape image <input type='file' name='img_input'></input></label>
    
    <br>
    <button type="submit" class="btn btn-secondary" value='save'>등록</button>
 </form> 
</form>
</div>
  </div>
  </section>

app/views/tapes/show.html.erb
<h1><%= @tape.title %></h1>


    <ul>

 <!--tape에 입힐 사진-->
        <!--<img src="..." alt="" class="upload_img">
        <li> <img src="<%= @tape.image %>"></li>-->
        
        <li><%=@tape.m1_singer %>-<%= @tape.m1_title%>
            <form action="/likes/:tape_id/create" method='post'>
                <input name='authenticity_token' type='hidden'value=<%= @token%>></input>
                <input id="mname" type="hidden" name="music_name" value=<%= @tape.m1_title %>></input>
                <input id="msinger" type="hidden" name="music_singer" value=<%= @tape.m1_singer %>></input>
                <input type="submit" value="submit"></input>
            </form>
        </li>
        <li><%=@tape.m2_singer %>-<%= @tape.m2_title%>
            <form action="likes/:tape_id/create" method='post'>
                <input name='authenticity_token' type='hidden'value=<%= @token%>></input>
                <input id="mname" type="hidden" name="music_name" value=<%= @tape.m2_title %>></input>
                <input id="msinger" type="hidden" name="music_singer" value=<%= @tape.m2_singer %>></input>
                <input type="submit" value="submit"></input>
            </form>
        </li>
        <li><%=@tape.m3_singer %>-<%= @tape.m3_title%>
            <form action="likes/:tape_id/create" method='post'>
                <input name='authenticity_token' type='hidden'value=<%= @token%>></input>
                <input id="mname" type="hidden" name="music_name" value=<%= @tape.m3_title %>></input>
                <input id="msinger" type="hidden" name="music_singer" value=<%= @tape.m3_singer %>></input>
                <input type="submit" value="submit"></input>
            </form>
        </li>
        <li><%=@tape.m4_singer %>-<%= @tape.m4_title%>
            <form action="likes/:tape_id/create" method='post'>
                <input name='authenticity_token' type='hidden'value=<%= @token%>></input>
                <input id="mname" type="hidden" name="music_name" value=<%= @tape.m4_title %>></input>
                <input id="msinger" type="hidden" name="music_singer" value=<%= @tape.m4_singer %>></input>
                <input type="submit" value="submit"></input>
            </form>
        </li>
        <li><%=@tape.m5_singer %>-<%= @tape.m5_title%>
            <form action="likes/:tape_id/create" method='post'>
                <input name='authenticity_token' type='hidden'value=<%= @token%>></input>
                <input id="mname" type="hidden" name="music_name" value=<%= @tape.m5_title %>></input>
                <input id="msinger" type="hidden" name="music_singer" value=<%= @tape.m5_singer %>></input>
                <input type="submit" value="submit"></input>
            </form>
        </li>
        <li><%=@tape.m6_singer %>-<%= @tape.m6_title%>
            <form action="likes/:tape_id/create" method='post'>
                <input name='authenticity_token' type='hidden'value=<%= @token%>></input>
                <input id="mname" type="hidden" name="music_name" value=<%= @tape.m6_title %>></input>
                <input id="msinger" type="hidden" name="music_singer" value=<%= @tape.m6_singer %>></input>
                <input type="submit" value="submit"></input>
            </form>
        </li>
        <li><%=@tape.m7_singer %>-<%= @tape.m7_title%>
            <form action="likes/:tape_id/create" method='post'>
                <input name='authenticity_token' type='hidden'value=<%= @token%>></input>
                <input id="mname" type="hidden" name="music_name" value=<%= @tape.m7_title %>></input>
                <input id="msinger" type="hidden" name="music_singer" value=<%= @tape.m7_singer %>></input>
                <input type="submit" value="submit"></input>
            </form>
        </li>
        <li><%=@tape.m8_singer %>-<%= @tape.m8_title%>
            <form action="likes/:tape_id/create" method='post'>
                <input name='authenticity_token' type='hidden'value=<%= @token%>></input>
                <input id="mname" type="hidden" name="music_name" value=<%= @tape.m8_title %>></input>
                <input id="msinger" type="hidden" name="music_singer" value=<%= @tape.m8_singer %>></input>
                <input type="submit" value="submit"></input>
            </form>
        </li>
        <li><%=@tape.m9_singer %>-<%= @tape.m9_title%>
            <form action="likes/:tape_id/create" method='post'>
                <input name='authenticity_token' type='hidden'value=<%= @token%>></input>
                <input id="mname" type="hidden" name="music_name" value=<%= @tape.m9_title %>></input>
                <input id="msinger" type="hidden" name="music_singer" value=<%= @tape.m9_singer %>></input>
                <input type="submit" value="submit"></input>
            </form>
        </li>
        <li><%=@tape.m10_singer %>-<%= @tape.m10_title%>
            <form action="likes/:tape_id/create" method='post'>
                <input name='authenticity_token' type='hidden'value=<%= @token%>></input>
                <input id="mname" type="hidden" name="music_name" value=<%= @tape.m10_title %>></input>
                <input id="msinger" type="hidden" name="music_singer" value=<%= @tape.m10_singer %>></input>
                <input type="submit" value="submit"></input>
            </form>
        </li>
    </ul>
<a href='/tapes'>다른 테이프로</a>
<a href='/tapes/<%= @tape.id%>' data-confirm ='삭제...하려고..?' data-method='delete'>삭제</a>
<a href='/tapes/<%= @tape.id%>/edit'>수정</a>