config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  root 'home#main_page'
  get 'my_page/index'
  resources :musics
  
  get 'home/fake_page' =>'home#fake_page'
  
  post "tapes/likes/:tape_id/create" => "likes#create"
  post "tapes/likes/:tape_id/destroy" => "like#destroy"
  post "daily/likes/:daily_id/create" => "likes#create"
  post "/daily/likes/:daily_id/create" => "likes#create"
  post "likes/:daily_id/create" => "likes#create"
  post "likes/:tape_id/create" => "likes#create"
  post "daily/likes/:daily_id/destroy" => "like#destroy"
  
  get '/tapes/new' =>'tapes#new'
  post '/tapes' =>'tapes#create'
  
  get '/tapes' => 'tapes#index'
  get '/tapes/:id' => 'tapes#show'
  
  get '/tapes/:id/edit' => 'tapes#edit'
  patch'/tapes/:id' =>'tapes#update'
  
  delete '/tapes/:id' => 'tapes#destroy'
  
  get '/daily' => 'daily#index'
  
  get '/daily/new' => 'daily#new'
  post '/daily' => 'daily#create'
  
  get '/daily/:id' => 'daily#show'
  
  get '/daily/:id/edit' => 'daily#edit'
  patch '/daily/:id' => 'daily#update'
  
  delete '/daily/:id' => 'daily#destroy'
  
  
  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="css/style.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Nanum+Brush+Script|Nanum+Gothic|Nanum+Myeongjo" rel="stylesheet">

</head>

<body>

<header> 

  <style>
    a:link  { text-decoration: none; color: black}
    a:visited {  text-decoration: none; color: black}
    a:active {  text-decoration: none; color: black}
    a:hover { text-decoration: none; color: black}
  </style>

    <nav class="nav">
      <div class="container">
        <div class="row">
          <div class="col-xl-4">
            <div class="logo">
            <img src="/assets/logo.png" class="logo_img" align="left">
            <a href="/"><p class="logo_text">늘어진 카세트 테이프</p></a>
            </div>
          </div>
          <div class="col-xl-4">
            <input class="search__input" type="text" placeholder="Song or Singer">
          </div>
          <% if user_signed_in? %>
          <div class="log-out">
            <%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %>
          </div>
          <% else %>
          <div class="col-xl-3">
            <%= link_to 'Sign in', new_user_session_path, method: 'get' %> &nbsp;
            <%= link_to 'Sign up', new_user_registration_path, method: 'get' %>
          </div>
          <% end %>
        </div>
      </div>
    </nav>
    
    
  

  <!--javascript-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
  
  <!-- <% if user_signed_in? %>-->
  <!--  <li class="item"><%= current_user.name %></li>-->
  <!--  <li class="item"><%= link_to 'My page', my_page_index_path, method: 'get' %></li>-->
  <!--  <li class="item"><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>-->
  <!--<% else %>-->
  <!--  <li class="item"></li>-->
  <!--  <li class="item"></li>-->
  <!--<% end %>-->
  
<%= yield %>

 <footer>
   <div>
     <div class="foot_logo"><b>©늘어진 카세트 테이프 2018</b></div>
     <div class="develop">developed by Young-Jin Kwon, Danbi Jung, No Yujung, Koo Daeun</div>
   </div>
 </footer>
</body>
</html>